name: qwentts
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cffi
  - charset-normalizer
  - pillow
  - pip
  - ffmpeg
  - libsndfile
  - numpy=1.26.4
  - packaging
  - setuptools
  - sox
  - wheel
  - pip:
      - -r requirements/pip-cpu.txt
